services:
  postgres:
    image: postgres:15
    container_name: eshop-postgres
    restart: always
    environment:
      POSTGRES_DB: eshop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"

  backend:
    build: .
    container_name: eshop-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: eshop_db
      PORT: 8000
