# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eshop-postgres
    restart: always
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: eshop-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres-data:
